language: c
compiler: gcc
before_install:
  - pip install --user cpp-coveralls
script: make travisbuild && make travistest
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

